spring:
  application:
    name: Shop
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}}/${DB_NAME}}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
key:
  access: jAFVmmF3sEBQCEEm8+VfanjExVccdl+PBuN1DZ18D14=
  refresh: XCNzSlrn6r8VCyJb5aJW0UgZae0vJEYwwfEJJg+CLrc=

message:
  hello: ${MESSAGE:Hello from Digital Ocean}