spring:
  application:
    name: Shop
  datasource:
    url: jdbc:postgresql://localhost:5432/g_36_shop
    username: postgres
    password: ppp77777
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
key:
  access: jAFVmmF3sEBQCEEm8+VfanjExVccdl+PBuN1DZ18D14=
  refresh: XCNzSlrn6r8VCyJb5aJW0UgZae0vJEYwwfEJJg+CLrc=

message:
  hello: Hello from Digital Ocean